name: CI (Qt Wallet PoC)

on:
  push:
  pull_request:

jobs:
  build-linux:
    name: Linux (Qt 6.5)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.5.3'
          host: 'linux'
          target: 'desktop'
      - name: Configure
        run: cmake -S . -B build
      - name: Build
        run: cmake --build build --parallel
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-binary
          path: build/qt_wallet_poc
          if-no-files-found: error

  build-macos:
    name: macOS (Qt 6.5)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.5.3'
          host: 'mac'
          target: 'desktop'
      - name: Configure
        run: cmake -S . -B build
      - name: Build
        run: cmake --build build --parallel
      - name: Zip .app bundle
        run: |
          cd build
          ditto -c -k --sequesterRsrc --keepParent qt_wallet_poc.app qt_wallet_poc-macos.zip
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-app
          path: build/qt_wallet_poc-macos.zip
          if-no-files-found: error

  build-windows:
    name: Windows (Qt 6.5)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.5.3'
          host: 'windows'
          target: 'desktop'
      - name: Configure
        run: cmake -S . -B build -A x64
      - name: Build
        run: cmake --build build --config Release --parallel
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-exe
          path: build/Release/qt_wallet_poc.exe
          if-no-files-found: error
